### ISSUE TITLE
poke实例里的小问题

### ISSUE THREAD

**Issue by madderscientist** [MRSlouzk/Nonebot-plugintutorials#3]
首先没import Message

其次_check错了，应该是
```
return event.target_id == event.self_id
```
（就不能让我这个cv工程师省心点吗www）

最后为什么私戳就报错啊（如下）
```
nonebot.adapters.onebot.exception.ActionFailed: <ActionFailed data=None, echo=1, msg=GROUP_NOT_FOUND, retcode=100, status=failed, wording=群聊不存在>
```

**Comment by XieXiLin3** [comment]
第1、2个问题，已对文档进行纠正，如果还有问题麻烦直接回复。
第三个……群聊不存在？可以试试返回群号，具体我也不明白。

**Comment by MRSlouzk** [comment]
> 首先没import Message
> 
> 其次_check错了，应该是
> 
> ```
> return event.target_id == event.self_id
> ```
> 
> （就不能让我这个cv工程师省心点吗www）
> 
> 最后为什么私戳就报错啊（如下）
> 
> ```
> nonebot.adapters.onebot.exception.ActionFailed: <ActionFailed data=None, echo=1, msg=GROUP_NOT_FOUND, retcode=100, status=failed, wording=群聊不存在>
> ```
第三个问题：我翻了一下Onebot文档，戳一戳事件(PokeNotifyEvent)目前仅支持群组，具体看[文档](https://github.com/botuniverse/onebot-11/blob/master/event/notice.md#%E7%BE%A4%E5%86%85%E6%88%B3%E4%B8%80%E6%88%B3)，还不支持私聊
